# Generated by Django 6.0.4 on 2026-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_categoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen'),
        ),
    ]
