# Generated by Django 6.0.4 on 2026-04-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_categoria_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="talle",
            field=models.CharField(
                choices=[
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                ],
                max_length=10,
                verbose_name="Talle",
            ),
        ),
    ]
