# Generated by Django 6.0.4 on 2026-06-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_usotela_producto_usos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de Pago (MP)'), ('Esperando_Transferencia', 'Esperando Transferencia'), ('Aprobado', 'Pago Aprobado'), ('Cancelado', 'Cancelado / Expirado'), ('Despachado', 'Pedido Despachado'), ('Enviado', 'Pedido Enviado')], default='Pendiente', max_length=30),
        ),
    ]
