# Generated by Django 6.0.4 on 2026-06-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_pedido_calle_pedido_ciudad_pedido_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='mp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='mp_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='mp_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
