# Generated by Django 6.0.4 on 2026-06-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_storeconfiguration_mp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='alias_bancario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alias Bancario para Transferencias'),
        ),
        migrations.AddField(
            model_name='storeconfiguration',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de Contacto'),
        ),
    ]
